spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moovsmart?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    data: classpath:/data.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          starttls.enable: true
          auth: true
          starttls.required: true
    url-activate: http://localhost:4200/activation/
    url-newpassword: http://localhost:4200/new-password/

logging:
  level:
    com.progmasters: debug
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

cors-policies: http://localhost:4200, http://127.0.0.1:4200, http://[::1]:4200

#    5am every day
purge:
  cron:
    expression: 0 0 5 * * ?

